from __future__ import annotations

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from app.routes import admin_router, alerts_router, auth_router, cases_router, logs_router, reports_router
from app.runtime import (
    SESSION_COOKIE,
    SESSION_ROLE_COOKIE,
    SESSION_TOKEN,
    AuthMiddleware,
    _current_role,
    _is_authenticated,
    _store_logs,
    _validate_live_tail_path,
    alert_context,
    alert_investigation,
    analytics_overview,
    case_detail,
    create_asset,
    create_backup,
    create_case,
    create_case_comment,
    create_ioc,
    create_policy,
    create_saved_view,
    create_suppression,
    daily_report_data,
    delete_case_comment,
    delta_report_data,
    get_alerts,
    get_case_comments,
    get_cases,
    get_logs,
    get_saved_views,
    get_stats,
    health,
    incidents_timeline,
    lifespan,
    link_case_alert,
    list_backups,
    playbook,
    restore_backup,
    risk_entities,
    settings,
    start_live_tail,
    tail_manager,
    update_alert,
)

app = FastAPI(title="Mini SOC Dashboard", lifespan=lifespan)
app.mount("/static", StaticFiles(directory="app/static"), name="static")
app.add_middleware(AuthMiddleware)

for router in (auth_router, logs_router, alerts_router, cases_router, reports_router, admin_router):
    app.include_router(router)

__all__ = [
    "SESSION_COOKIE",
    "SESSION_ROLE_COOKIE",
    "SESSION_TOKEN",
    "AuthMiddleware",
    "_current_role",
    "_is_authenticated",
    "_store_logs",
    "_validate_live_tail_path",
    "alert_context",
    "alert_investigation",
    "analytics_overview",
    "app",
    "case_detail",
    "create_asset",
    "create_backup",
    "create_case",
    "create_case_comment",
    "create_ioc",
    "create_policy",
    "create_saved_view",
    "create_suppression",
    "daily_report_data",
    "delete_case_comment",
    "delta_report_data",
    "get_alerts",
    "get_case_comments",
    "get_cases",
    "get_logs",
    "get_saved_views",
    "get_stats",
    "health",
    "incidents_timeline",
    "link_case_alert",
    "list_backups",
    "playbook",
    "restore_backup",
    "risk_entities",
    "settings",
    "start_live_tail",
    "tail_manager",
    "update_alert",
]
